---
- name: Création du superutilisateur NetBox
  ansible.builtin.shell: |
    /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py shell -c "
    from django.contrib.auth import get_user_model;
    User = get_user_model();
    if not User.objects.filter(username='{{ netbox_superuser_name }}').exists():
        User.objects.create_superuser(
            '{{ netbox_superuser_name }}',
            '{{ netbox_superuser_email }}',
            '{{ netbox_superuser_password }}'
        )
        print('Superuser created')
    else:
        print('Superuser already exists')
    "
  register: netbox_superuser_result
  changed_when: "'Superuser created' in netbox_superuser_result.stdout"
