---
netbox_logs_to_elasticsearch_enabled: true
netbox_filebeat_service_log_paths:
  - /var/log/syslog
  - /var/log/messages

netbox_filebeat_service_include_lines:
  - "netbox"
  - "netbox-rq"

netbox_filebeat_nginx_log_paths:
  - /var/log/nginx/access.log
  - /var/log/nginx/error.log
