---
netbox_logs_to_elasticsearch_enabled: true

netbox_filebeat_journald_units:
  - netbox.service
  - netbox-rq.service

netbox_filebeat_nginx_log_paths:
  - /var/log/nginx/access.log
  - /var/log/nginx/error.log
