---
- name: Mise à jour des packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
    cache_valid_time: 3600

- name: Installation des outils de base
  ansible.builtin.apt:
    name:
      - curl
      - git
      - vim
      - htop
      - net-tools
      - unzip
      - fail2ban
    state: present

- name: Configuration du timezone
  community.general.timezone:
    name: Europe/Paris

- name: Démarrage et activation de fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
